#!/bin/bash

# Copyright (C) 2023 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials,
# and your use of them is governed by the express license under which they
# were provided to you ("License"). Unless the License provides otherwise,
# you may not use, modify, copy, publish, distribute, disclose or transmit
# this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express
# or implied warranties, other than those that are expressly stated in the License.

set -e

SCENESCAPE_IMAGE=scenescape-manager
DBDIR=db
MIGRATIONSDIR=migrations
SECRETSDIR=secrets
CHECK_ONLY=0
APPDIR=/workspace

function wait_for_container()
{
  CONTAINERNAME=$1
  WAITFORSTRING=${2:-"Container is ready"}
  MAX_WAIT=60
  CUR_WAIT=0
  CONTAINER_READY=0
  while [ -z "$(docker ps -q -f name=^/${CONTAINERNAME}$ )" ]
  do
    sleep 1
    CUR_WAIT=$(( $CUR_WAIT+1 ))
    if [[ $CUR_WAIT -ge $MAX_WAIT ]]
    then
      echo "Error: Failed to start ${CONTAINERNAME} container."
      test_int
    fi
  done

  while true
  do
    if docker logs ${CONTAINERNAME} 2>&1 | grep -q "${WAITFORSTRING}"
    then
      CONTAINER_READY=1
      break
    fi
    sleep 1
    CUR_WAIT=$(( $CUR_WAIT+1 ))
    if [[ $CUR_WAIT -ge $MAX_WAIT ]]
    then
      echo "Warning: Failed detecting start of container $CONTAINERNAME."
      break
    fi
  done
}

while [ $# -gt 0 -a x$(expr substr "${1:-empty}" 1 2) = "x--" ] ; do
    case "$1" in
        --check)
            CHECK_ONLY=1
            shift
            ;;
    esac
done

NOW=$(date +"%y%m%d-%H%M%S")
PG_CONTAINER=pg_backup
PG_UID=$(stat -c '%u' ${DBDIR})
PG_DB_VERSION=$(cat ${DBDIR}/PG_VERSION)
PG_NEW_VERSION=$(docker run --rm ${SCENESCAPE_IMAGE} /bin/sh -c \
                 'echo -n PG_NEW_VERSION= ; ls /usr/lib/postgresql' \
                     | awk -F= '/PG_NEW_VERSION/{print $2}' | tr -d '\015')
if [ -z "${PG_NEW_VERSION}" ] ; then
    echo Unknown Postgres version
    exit 1
fi
if [ "${PG_NEW_VERSION}" -le "${PG_DB_VERSION}" ] ; then
    echo Postgres server version ${PG_NEW_VERSION} is not newer than existing database version ${PG_DB_VERSION}

    docker run \
        --name ${PG_CONTAINER} \
        --rm \
        -d \
        --workdir ${APPDIR} \
        -v ${PWD}:${APPDIR} \
        --privileged \
        -e PYTHONPATH=${APPDIR} \
        ${SCENESCAPE_IMAGE} \
        database
    wait_for_container ${PG_CONTAINER}

    MIGRATION_NEEDED=1
    if ! docker exec -it ${PG_CONTAINER} /bin/bash sscape/tools/migration --check ; then
        echo No migration needed
        MIGRATION_NEEDED=0
    fi
    docker stop ${PG_CONTAINER}
    if [ ${MIGRATION_NEEDED} = 0 ] ; then
        exit 1
    fi
fi
if [ ${CHECK_ONLY} = 1 ] ; then
    exit 0
fi

DBPASS=$(sed -r -n -e "/DATABASE_PASSWORD=/s/.*'([^']+)'/\1/p" \
                 ${DBDIR}/../secrets/django/secrets.py)
BACKUP=${DBDIR}-backup-${NOW}

docker stop ${PG_CONTAINER} >/dev/null 2>&1 || true

mkdir ${BACKUP}
rsync -a ${DBDIR} ${MIGRATIONSDIR} ${BACKUP}/.
mv ${BACKUP}/${DBDIR}/pg_hba.conf ${BACKUP}/${DBDIR}/pg_hba.conf-orig
cat > ${BACKUP}/${DBDIR}/pg_hba.conf <<EOF
local all all trust
host all all 0.0.0.0/0 trust
EOF

# Start postgres container using version that matches existing database
docker run \
       --name ${PG_CONTAINER} \
       --rm \
       -e POSTGRES_PASSWORD="${DBPASS}" \
       -e POSTGRES_USER=scenescape \
       -e POSTGRES_HOST_AUTH_METHOD=trust \
       -v ${PWD}/${BACKUP}/${DBDIR}:/var/lib/postgresql/data \
       --entrypoint="/bin/bash" \
       -d \
       postgres:${PG_DB_VERSION} \
       -c "usermod --uid=${PG_UID} postgres ; id postgres ; exec docker-entrypoint.sh postgres"

wait_for_container ${PG_CONTAINER} "database system is ready to accept connections"

# Create backup of database
docker exec ${PG_CONTAINER} /bin/bash -c 'su postgres -c "pg_dump -U scenescape"' \
       > ${BACKUP}.psql

docker stop ${PG_CONTAINER}

mv ${BACKUP}/${DBDIR}/pg_hba.conf-orig ${BACKUP}/${DBDIR}/pg_hba.conf

NEWDB="${DBDIR}-v${PG_NEW_VERSION}-${NOW}"
mkdir -p "${NEWDB}"
rsync -a ${MIGRATIONSDIR} ${SECRETSDIR} ${NEWDB}/.

if [ "${PG_NEW_VERSION}" -le "${PG_DB_VERSION}" ] ; then
    echo Copying old database
    rsync -a --delete "${DBDIR}" "${NEWDB}/."
else
    # Create new db using new version of postgres
    mkdir -p "${NEWDB}/${DBDIR}"
    PG_UID=$(stat -c '%u' ${NEWDB})

    docker run \
           --name ${PG_CONTAINER} \
           --rm \
           -e POSTGRES_PASSWORD="${DBPASS}" \
           -e POSTGRES_USER=scenescape \
           -e POSTGRES_HOST_AUTH_METHOD=trust \
           -e LANG=C.UTF-8 \
           -v ${PWD}/${NEWDB}/${DBDIR}:/var/lib/postgresql/data \
           --entrypoint="/bin/bash" \
           -d \
           postgres:${PG_NEW_VERSION} \
           -c "usermod --uid=${PG_UID} postgres ; id postgres ; exec docker-entrypoint.sh postgres"

    sleep 30

    # Create new version of database from backup of old database
    docker cp ${BACKUP}.psql ${PG_CONTAINER}:/tmp/$(basename ${BACKUP}.psql)
    docker exec ${PG_CONTAINER} /bin/bash \
           -c "su postgres -c 'psql -U scenescape -d scenescape < /tmp/$(basename ${BACKUP}.psql)'"
    cp "${DBDIR}/pg_hba.conf" "${NEWDB}/${DBDIR}"

    docker stop ${PG_CONTAINER}
fi

# Run migration
docker run \
       --name ${PG_CONTAINER} \
       --rm \
       -d \
       --workdir ${APPDIR} \
       -v ${PWD}:${APPDIR} \
       -v ${PWD}/${NEWDB}/db:${APPDIR}/db \
       -v ${PWD}/${NEWDB}/migrations:${APPDIR}/migrations \
       --privileged \
       -e PYTHONPATH=${APPDIR} \
       ${SCENESCAPE_IMAGE} \
       database

wait_for_container ${PG_CONTAINER}

docker exec -it ${PG_CONTAINER} /bin/bash sscape/tools/migration
docker stop ${PG_CONTAINER}

rm -rf ${NEWDB}/${SECRETSDIR}

echo "Database has been copied to: ${BACKUP}"
echo "               backed up to: ${BACKUP}.psql"
echo
echo "Upgraded database for Postgres ${PG_NEW_VERSION} has been created: ${NEWDB}"
