# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel-Edge-Software
# This file is licensed under the Limited Edge Software Distribution License Agreement.
# See the LICENSE file in the root of this repository for details.

IMAGE := scenescape-camcalibration
RUNTIME_OS_IMAGE := ubuntu:22.04

include ../common.mk

default: build-image
