# -*- mode: Fundamental; indent-tabs-mode: nil -*-

# Copyright (C) 2023 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials,
# and your use of them is governed by the express license under which they
# were provided to you ("License"). Unless the License provides otherwise,
# you may not use, modify, copy, publish, distribute, disclose or transmit
# this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express
# or implied warranties, other than those that are expressly stated in the License.

FROM ubuntu:22.04

COPY docker/Makefile /root/docker/Makefile
COPY docker/user_access_config.json /root/docker/user_access_config.json
COPY certificates/Makefile /root/certificates/Makefile
COPY certificates/openssl.cnf /root/certificates/openssl.cnf
COPY version.txt /root/sscape/version.txt

RUN apt-get update && apt-get install -y curl make python3

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl

CMD ["/bin/bash"]
