# Copyright (C) 2021-2024 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials,
# and your use of them is governed by the express license under which they
# were provided to you ("License"). Unless the License provides otherwise,
# you may not use, modify, copy, publish, distribute, disclose or transmit
# this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express
# or implied warranties, other than those that are expressly stated in the License.

PERF_TESTS_PATH=tests/perf_tests
define perf-recipe =
	$(eval TEST_SCRIPT=$1)
	$(eval LOGFILE=$(TEST_DATA)/perf/$@-$(shell date -u +"%F-%T").log)
	@set -ex \
	  ; echo RUNNING TEST $@ \
	  ; cd .. \
	  ; mkdir -p $(shell dirname $(LOGFILE)) \
	  ; env IMAGE=$(IMAGE):$(VERSION) BROWSER_IMAGE=$(IMAGE)-interface:$(VERSION) $(PERF_TESTS_PATH)/$(TEST_SCRIPT) 2>&1 | tee -i $(LOGFILE) \
	  ; echo "MAKE_TARGET: $@" | tee -ia $(LOGFILE) \
	  ; echo END TEST $@
endef

performance_tests:
	$(MAKE) -Otarget -j 1 _performance_tests SUPASS=$(SUPASS) -k

_performance_tests: \
  inference-conformance \
  inference-performance \
  inference-threading \
  scene-performance \
  default-models \
  quick-test-model \
  load-config-models \
  geometry-conformance \

geometry-conformance: \
  point-conformance \
  line-conformance \

# Recipes below must be in alphabetical order

default-models: # SAIL-T487
	$(call perf-recipe, tc_default_models.sh)

quick-test-model: # SAIL-T537
	$(call perf-recipe, tc_quick_test_model.sh)

load-config-models: # SAIL-T488
	$(call perf-recipe, tc_load_config_models.sh)

inference-conformance: # SAIL-T495
	$(call perf-recipe, tc_inference_conformance.sh)

inference-performance: # SAIL-T494
	$(call perf-recipe, tc_inference_performance.sh)

inference-threading: # SAIL-T508
	$(call perf-recipe, tc_inference_threading.sh)

scene-performance: # SAIL-T496
	$(call perf-recipe, tc_scene_performance.sh)

scene-performance-full: # SAIL-T608
	# 2 Cameras at 10fps, 2 models
	$(eval TARGET_RATE ?= 40)
	$(call perf-recipe, tc_scene_performance_full --target $(TARGET_RATE))

# Compare C++ geometry implementation
# vs original python implementation.
point-conformance:
	$(eval LOGDIR=$(TEST_DATA)/infra)
	$(eval LOGFILE=$(LOGDIR)/$@-$(shell date -u +"%F-%T").log)
	@set -ex \
          ; echo RUNNING TEST $@ \
          ; cd .. \
          ; mkdir -p $(LOGDIR) \
          ; docker/scenescape-start $(PERF_TESTS_PATH)/tc_geometry_point.py | tee -ia $(LOGFILE) \
          ; echo END TEST $@

line-conformance:
	$(eval LOGDIR=$(TEST_DATA)/infra)
	$(eval LOGFILE=$(LOGDIR)/$@-$(shell date -u +"%F-%T").log)
	@set -ex \
          ; echo RUNNING TEST $@ \
          ; cd .. \
          ; mkdir -p $(LOGDIR) \
          ; docker/scenescape-start $(PERF_TESTS_PATH)/tc_geometry_line.py | tee -ia $(LOGFILE) \
          ; echo END TEST $@
