# Copyright (C) 2021-2024 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials,
# and your use of them is governed by the express license under which they
# were provided to you ("License"). Unless the License provides otherwise,
# you may not use, modify, copy, publish, distribute, disclose or transmit
# this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express
# or implied warranties, other than those that are expressly stated in the License.

SSCAPE_TESTS_PATH=tests/sscape_tests

define unit-docker-compose-recipe=
	$(eval TEST_FOLDER=$1)
	$(eval YML_FILENAME=$2)
	$(eval TEST_IMAGE=$3)
	$(eval DBROOT=$(TEST_DATA)/db_$@)
	$(eval LOGFILE=$(TEST_DATA)/unit/$@-$(shell date -u +"%F-%T").log)
	@set -ex \
	  ; echo RUNNING TEST $@ \
	  ; cd .. \
	  ; mkdir -p $(shell dirname $(LOGFILE)) \
	  ; $(SSCAPE_TESTS_PATH)/secrets.sh \
	  ; env SECRETSDIR=secrets LOGSFORCONTAINER="mqtt_publish" IMAGE=$(IMAGE):$(VERSION) BROWSER_IMAGE=$(TEST_IMAGE):$(VERSION) DBROOT=$(DBROOT) $(RUNTEST) $(YML_FILENAME) \
	  $(UNIT_TEST_COVERAGE_CMD) --source=sscape/ -m pytest -s $(GENERATE_JUNITXML_UNITTEST) $(SSCAPE_TESTS_PATH)/$(TEST_FOLDER)/ 2>&1 | tee -i $(LOGFILE) \
	  ; echo "MAKE_TARGET: $@" | tee -ia $(LOGFILE) \
	  ; echo END TEST $@
endef

define unit-recipe=
	$(eval TEST_FOLDER=$1)
	$(eval DOCKER_IMAGE=$2)
	$(eval DOCKER_IMAGE=$(if $(DOCKER_IMAGE), $(DOCKER_IMAGE), $(IMAGE)))
	$(eval LOGFILE=$(TEST_DATA)/unit/$@-$(shell date -u +"%F-%T").log)
	@set -ex \
	  ; echo RUNNING TEST $@ \
	  ; cd .. \
	  ; mkdir -p $(shell dirname $(LOGFILE)) \
	  ; $(SSCAPE_TESTS_PATH)/secrets.sh \
	  ; docker/scenescape-start --image $(DOCKER_IMAGE) sh -c "$(UNIT_TEST_COVERAGE_CMD) --source=sscape/ -m pytest -s $(GENERATE_JUNITXML_UNITTEST) $(SSCAPE_TESTS_PATH)/$(TEST_FOLDER)/" 2>&1 | tee -i $(LOGFILE) \
	  ; echo "MAKE_TARGET: $@" | tee -ia $(LOGFILE) \
	  ; echo END TEST $@
endef

define unit-django-recipe=
	$(eval TEST_FOLDER=$1)
	$(eval DOCKER_IMAGE=$2)
	$(eval DOCKER_IMAGE=$(if $(DOCKER_IMAGE), $(DOCKER_IMAGE), $(IMAGE)))
	$(eval LOGFILE=$(TEST_DATA)/unit/$@-$(shell date -u +"%F-%T").log)
	@set -ex \
	  ; echo RUNNING TEST $@ \
	  ; cd .. \
	  ; mkdir -p $(shell dirname $(LOGFILE)) \
	  ; $(SSCAPE_TESTS_PATH)/secrets.sh \
	  ; docker/scenescape-start --image $(DOCKER_IMAGE) sh -c "$(UNIT_TEST_COVERAGE_CMD) --source=sscape/ -m pytest -s $(GENERATE_JUNITXML_UNITTEST) --ds=tests.sscape_tests.settings_unittest $(SSCAPE_TESTS_PATH)/$(TEST_FOLDER)/" 2>&1 | tee -i $(LOGFILE) \
	  ; echo "MAKE_TARGET: $@" | tee -ia $(LOGFILE) \
	  ; echo END TEST $@
endef

# Recipes below must be in alphabetical order

autocamcalib-unit: # SAIL-T576
	$(call unit-recipe, autocamcalib, $(IMAGE)-camcalibration)

detector-unit: # SAIL-T565
	make -C ../docker install-models MODELS=ocr
	$(call unit-docker-compose-recipe, detector, $(COMPOSE)/ovms.yml, $(IMAGE)-percebro)

geometry-unit: # SAIL-T570
	$(call unit-recipe, geometry)

geospatial-unit: # SAIL-T610
	$(call unit-recipe, geospatial)

markerless-unit: # SAIL-T617
	$(call unit-docker-compose-recipe, markerless, $(COMPOSE)/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/web.yml:$(COMPOSE)/camcalibration.yml, $(IMAGE)-camcalibration)

mesh-util-unit: #SAIL-T355
	$(call unit-recipe, mesh_util)

realsense-unit: # SAIL-T572
	$(call unit-recipe, realsense, $(IMAGE)-percebro)

scene-unit: # SAIL-T567
	$(call unit-recipe, scene_pytest, $(IMAGE)-controller)

scenescape-unit: # SAIL-T566
	$(call unit-recipe, scenescape)

schema-unit: # SAIL-T575
	$(call unit-recipe, schema)

sscape-unit: # SAIL-T616
	echo RUNNING TEST $@
	cd .. ; \
	env SECRETSDIR=/workspace/secrets docker/scenescape-start sh -c \
	  "$(SSCAPE_TESTS_PATH)/secrets.sh \
	  ; COVERAGE_FILE=.coverage_sscape $(COVERAGE_CMD) --branch --omit=*/dist-packages/*,*/opt/intel/* --context=sscape-unit \
	  ./manage.py test --settings=tests.sscape_tests.settings_unittest tests.sscape_tests" ;
	echo END TEST $@

timestamp-unit: # SAIL-T599
	$(call unit-recipe, timestamp)

transform-unit: # SAIL-T632
	$(call unit-recipe, transform, $(IMAGE)-controller)

videosource-unit: # SAIL-T569
	$(call unit-recipe, videosource, $(IMAGE)-percebro)

views-unit: # SAIL-T598
	$(call unit-django-recipe, views)
