# -*- mode: Fundamental; indent-tabs-mode: nil -*-

# Copyright (C) 2021-2025 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials,
# and your use of them is governed by the express license under which they
# were provided to you ("License"). Unless the License provides otherwise,
# you may not use, modify, copy, publish, distribute, disclose or transmit
# this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express
# or implied warranties, other than those that are expressly stated in the License.

FROM ubuntu:22.04 AS build-stage

# We use root for runtime init. The command in ENTRYPOINT will drop to an unprivileged user.
# hadolint ignore=DL3002
USER root

SHELL ["/bin/bash", "-e", "-o", "pipefail", "-c"]

ARG USER_ID
ARG CERTDOMAIN=scenescape.intel.com

ENV DEBIAN_FRONTEND=noninteractive
ENV TRACKED_DIRS="bin boot etc home lib lib32 lib64 libx32 media mnt opt root sbin srv usr"

RUN : \
    ; apt-get update \
    ; apt-get install -y --no-install-recommends git

WORKDIR /

COPY .gitignore .
RUN cd / \
    && git init \
    && git config user.email "you@example.com" && git config user.name "Your Name" \
    && git add ${TRACKED_DIRS} \
    && git commit -m "Initial commit"

RUN : \
    ; apt-get update \
    ; apt-get install -y --no-install-recommends \
        # Keep package list in alphabetical order
        cmake \
        curl \
        g++ \
        git \
        libeigen3-dev \
        libglib2.0-0 \
        libgl1-mesa-glx \
        libgtest-dev \
        libopencv-dev \
        make \
        netbase \
        patch \
        pybind11-dev \
        python-is-python3 \
        python3-pip \
        python3-scipy \
        python3-venv \
        sudo \
    && apt-get purge -y python3-numpy \
    && pip3 install --upgrade --no-cache-dir pip \
    && rm -rf /var/lib/apt/lists/*

RUN git add ${TRACKED_DIRS} && git commit -m "Layer 1: base packages"

# ENV ENV_DIR=/venv
#
# COPY requirements-controller.txt /tmp
# RUN : \
#     ; mkdir ${ENV_DIR} \
#     ; python3 -m venv ${ENV_DIR} \
#     ; ${ENV_DIR}/bin/pip3 install --upgrade --no-cache-dir -r /tmp/requirements-controller.txt \
#     ; rm -rf /tmp/requirements-controller.txt
#
# ENV TRACKED_DIRS="${TRACKED_DIRS} ${ENV_DIR}"
# RUN git add ${TRACKED_DIRS} && git commit -m "Layer 2: controller python dependencies"
