define CAMCALIBFILES
atag_camera_calibration_controller.py \
atag_camera_calibration.py \
auto_camera_calibration_context.py \
auto_camera_calibration_controller.py \
auto_camera_calibration_model.py \
camcalibration \
markerless_camera_calibration_controller.py \
markerless_camera_calibration.py \
polycam_to_images.py
endef
