# -*- mode: Fundamental; indent-tabs-mode: nil -*-

# Copyright (C) 2021 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials,
# and your use of them is governed by the express license under which they
# were provided to you ("License"). Unless the License provides otherwise,
# you may not use, modify, copy, publish, distribute, disclose or transmit
# this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express
# or implied warranties, other than those that are expressly stated in the License.

FROM ubuntu:22.04

# We use root for runtime init. The command in ENTRYPOINT will drop to an unprivileged user.
# hadolint ignore=DL3002
USER root

SHELL ["/bin/bash", "-e", "-o", "pipefail", "-c"]

ENV DEBIAN_FRONTEND=noninteractive

RUN : \
    ; apt-get update \
    ; install -d -m 0755 /etc/apt/keyrings \
    ; apt-get install -y --no-install-recommends \
        wget \
        curl \
        libpci-dev \
        libnss3-tools \
        python3 \
        python3-pip \
        software-properties-common \
        sudo \
        unzip \
        xserver-xephyr \
        xvfb \
    ; wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null \
    ; echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null \
    ; echo -e ' \n\
Package: * \n\
Pin: origin packages.mozilla.org \n\
Pin-Priority: 1000 \n\
' | tee /etc/apt/preferences.d/mozilla \
    ; apt-get update && apt-get install -y --no-install-recommends firefox \
    ; rm -rf /var/lib/apt/lists/*

# Python modules
COPY ./docker/requirements-interface.txt /tmp
RUN : \
    ; pip3 install --no-cache-dir -r /tmp/requirements-interface.txt \
    ; rm -rf /tmp/requirements-interface.txt \
    ;

# Gecko Driver
ADD ./docker/geckodriver.tar.gz /usr/local/bin/

ENV WSUSER selenium
RUN : \
    ; useradd -r -m -s /bin/bash $WSUSER && eval WSHOME=~$WSUSER \
    ;

# Be sure to update this line if the user or home directory changes
COPY ./docker/firefox-profile.tar /home/selenium/.mozilla/

RUN : \
    ; eval WSHOME=~$WSUSER \
    ; chown -R "$WSUSER.$WSUSER" "$WSHOME/.mozilla" \
    ;

COPY ./docker/sel-init /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/sel-init"]
