#!/bin/bash

# Copyright (C) 2021 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials,
# and your use of them is governed by the express license under which they
# were provided to you ("License"). Unless the License provides otherwise,
# you may not use, modify, copy, publish, distribute, disclose or transmit
# this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express
# or implied warranties, other than those that are expressly stated in the License.

set -e

WSUSER=${WSUSER:-selenium}
WORKSPACE=${WORKSPACE:-/workspace}
SECRETSDIR=${SECRETSDIR:-${WORKSPACE}/secrets}
RUNSECRETS=/run/secrets

eval WSHOME=~${WSUSER}

fix_uid()
{
    if (($WSUID < 1000)) ; then
        WSDIR=${HOSTDIR}
        if [ -z "${WSDIR}" ] ; then
            WSDIR=${WORKSPACE}
        fi
        echo "Owner of ${WSDIR} is system user. Aborting."
        exit 1
    fi
    if [ ${WSGID} != $(id -g ${WSUSER}) ] ; then
        groupmod -g ${WSGID} ${WSUSER}
    fi
    if [ ${WSGID} != $(id -g ${WSUSER}) -o ${WSUID} != $(id -u ${WSUSER}) ] ; then
        usermod -u ${WSUID} -g ${WSGID} ${WSUSER}
    fi
}

if [ -d "${WORKSPACE}" ] ; then
    WSUID=$(stat -c '%u' "${WORKSPACE}")
    WSGID=$(stat -c '%g' "${WORKSPACE}")
    fix_uid

    # Create a bind mount to the same location of the host dir
    if [ -n "${HOSTDIR}" ] ; then
        mkdir -p "${HOSTDIR}"
        mount --bind "${WORKSPACE}" "${HOSTDIR}"
        cd "${HOSTDIR}"
    else
        cd "${WORKSPACE}"
    fi
elif [ -e ${WSHOME}/.Xauthority ] ; then
    WSUID=$(stat -c '%u' ${WSHOME}/.Xauthority)
    WSGID=$(stat -c '%g' ${WSHOME}/.Xauthority)
    fix_uid
fi

while [ $# -gt 0 -a x$(expr substr "$1" 1 2) = "x--" ] ; do
    case "$1" in
        --shell)
            DO_SHELL=user
            shift
            ;;
        --super-shell)
            DO_SHELL=super
            shift
            ;;
        *)
            echo "Unknown flag $1"
            exit 1
    esac
done

if [ -n "${SECRETSDIR}" ] ; then
    case "${SECRETSDIR}" in
        /* )
            ;;
        * )
            SECRETSDIR=${WORKSPACE}/${SECRETSDIR}
            ;;
    esac
fi
if [ ! -e ${RUNSECRETS} -a -n "${SECRETSDIR}" -a -d "${SECRETSDIR}" ] ; then
    echo Found some secrets
    ln -s ${SECRETSDIR} ${RUNSECRETS}
fi
if [ -e ${RUNSECRETS}/certs/scenescape-ca.pem ] ; then
    PROFILEDIR=${WSHOME}/.mozilla/firefox/scenescape.default
    sudo -u ${WSUSER} certutil -A \
         -d ${PROFILEDIR} \
         -i ${RUNSECRETS}/certs/scenescape-ca.pem \
         -t TCu,Cuw,Tuw \
         -n "SceneScape Root CA"
else
    ls -Fla ${RUNSECRETS}
fi

if [ -n "${WAITPID}" ] ; then
    IFS=' '
    for pid in ${WAITPID} ; do
        # wait ${pid}
        tail --pid=${pid} -f /dev/null
    done
    exit 0
elif [ "$DO_SHELL" = 'user' ] ; then
    if [ $# -gt 0 ] ; then
#       echo "Starting shell with command: $@"
        IFS=
        exec sudo -u ${WSUSER} -E -H -s $@
    else
#       echo "Starting shell"
        exec su ${WSUSER}
    fi
elif [ "$DO_SHELL" = 'super' ] ; then
    if [ $# -gt 0 ] ; then
#       echo "Starting super shell with command: $@"
        exec /bin/bash -c "$@"
    else
#       echo "Starting super shell"
        exec /bin/bash
    fi
else
    if [ $# -gt 0 ] ; then
        IFS=
        exec sudo -u ${WSUSER} -E -H $@
    else
        exec su ${WSUSER}
    fi
fi
