#!/usr/bin/env python3

# SPDX-FileCopyrightText: (C) 2023 - 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

import argparse
import logging
import os

from auto_camera_calibration_context import CameraCalibrationContext
from auto_camera_calibration_api import CameraCalibrationApi

# Configure logging
log_level = os.getenv("LOG_LEVEL", "ERROR").upper()
logging.basicConfig(level=getattr(logging, log_level, logging.ERROR), force=True)
log = logging.getLogger("autocalibration")

def build_argparser():
  parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
  parser.add_argument("--resturl", default="https://web.scenescape.intel.com/api/v1",
                      help="URL of REST API")
  parser.add_argument("--restauth", required=True,
                      help="user:password or JSON file for REST authentication")
  parser.add_argument("--rootcert", default="/run/secrets/certs/scenescape-ca.pem",
                      help="path to ca certificate")
  parser.add_argument("--cert",
                      help="path to client certificate")
  parser.add_argument('--restport', type=int, default=8443, help='Exposed REST API server port')
  parser.add_argument("--ssl-certfile", required=True, help="SSL certificate file path")
  parser.add_argument("--ssl-keyfile", required=True, help="SSL private key file path")
  return parser

def main():
  args = build_argparser().parse_args()
  print("Auto Camera Calibration Container started")
  camera_calibration_controller = CameraCalibrationContext(
      args.cert,
      args.rootcert,
      args.resturl,
      args.restauth,
  )

  camera_calibration_controller.preprocess_scenes()
  api = CameraCalibrationApi(camera_calibration_controller)
  api.start(
    port=args.restport,
    ssl_cert=args.ssl_certfile,
    ssl_key=args.ssl_keyfile
  )
  return

if __name__ == '__main__':
  exit(main() or 0)
