define PERCEBROFILES
beancount.sh \
detector_3d.py \
detector_atag.py \
detector_ds.py \
detector_geti.py \
detector_motion.py \
detector_ocr.py \
detector.py \
detector_tesseract.py \
detector_yolo.py \
framebuffer.py \
inferizer.py \
modelchain.py \
model-config.json \
percebro \
percsim \
README.md \
realsense.py \
sensor.py \
vcr.py \
videoframe.py \
videosource.py \
wrapper_otxssd.py \
utils/waitforbroker
endef
