#!/bin/bash

# Copyright (C) 2024 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials,
# and your use of them is governed by the express license under which they
# were provided to you ("License"). Unless the License provides otherwise,
# you may not use, modify, copy, publish, distribute, disclose or transmit
# this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express
# or implied warranties, other than those that are expressly stated in the License.

# FIXME This example, make sure that '.scenescape' is added to the no_proxy environment
# variable

KUB_CLUSTER_FRP_ADDRESS=${KUB_CLUSTER_FRP_ADDRESS:-"host.docker.internal"}
KUB_CLUSTER_FRP_PORT=${KUB_CLUSTER_FRP_PORT:-"8080"}
KUB_CLUSTER_FRP_SECRET_KEY=${KUB_CLUSTER_FRP_SECRET_KEY:-"abcdefg"}
CERT_KUB_BROKER_URL=${CERT_KUB_BROKER_URL:-"broker.scenescape"}
CERT_KUB_WEB_URL=${CERT_KUB_WEB_URL:-"web.scenescape"}
PYTEST_KUB_WEB_URL="https://$CERT_KUB_WEB_URL"
PYTEST_KUB_REST_URL="$PYTEST_KUB_WEB_URL/api/v1"
