#!/bin/bash

# Copyright (C) 2023-2024 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials,
# and your use of them is governed by the express license under which they
# were provided to you ("License"). Unless the License provides otherwise,
# you may not use, modify, copy, publish, distribute, disclose or transmit
# this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express
# or implied warranties, other than those that are expressly stated in the License.

TEST_NAME="SAIL-T613"
FILES=(rvfiles uifiles)
TEMP_EXT="tmp"
STATUS="${#FILES[@]}"

echo "Executing: ${TEST_NAME}"
# Change the directory to the base folder
cd "$(dirname "$0")"/../../ && pwd

for file in "${FILES[@]}"; do

    if [ "$file" == "rvfiles" ]; then
        LOC_DIR="controller/docker"
    else
        LOC_DIR="manager/docker"
    fi

    mv "$LOC_DIR/Makefile.$file" "$LOC_DIR/Makefile.$file.$TEMP_EXT"

    echo "Generate the latest Makefile.$file"
    make -C $LOC_DIR "Makefile.$file"

    if ! diff "$LOC_DIR/Makefile.$file" "$LOC_DIR/Makefile.$file.$TEMP_EXT"; then
        echo "File '$LOC_DIR/Makefile.$file' should be regenerated!"
    else
        echo "File '$LOC_DIR/Makefile.$file' is up-to-date."
        ((STATUS--))
    fi

    mv "$LOC_DIR/Makefile.$file.$TEMP_EXT" "$LOC_DIR/Makefile.$file"
done

if [[ $STATUS -eq 0 ]] ; then
    echo "${TEST_NAME}: PASS"
else
    echo "${TEST_NAME}: FAIL"
fi

exit "$STATUS"
